[2025-07-24T16:21:06.438+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T16:21:06.470+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_songs manual__2025-07-24T16:20:55.060184+00:00 [queued]>
[2025-07-24T16:21:06.481+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_songs manual__2025-07-24T16:20:55.060184+00:00 [queued]>
[2025-07-24T16:21:06.482+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-24T16:21:06.499+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Stage_songs> on 2025-07-24 16:20:55.060184+00:00
[2025-07-24T16:21:06.509+0000] {standard_task_runner.py:63} INFO - Started process 187 to run task
[2025-07-24T16:21:06.516+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_pipeline', 'Stage_songs', 'manual__2025-07-24T16:20:55.060184+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/final_exam_src.py', '--cfg-path', '/tmp/tmp47ui_054']
[2025-07-24T16:21:06.521+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask Stage_songs
[2025-07-24T16:21:06.613+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_pipeline.Stage_songs manual__2025-07-24T16:20:55.060184+00:00 [running]> on host a0f12fcdcc8f
[2025-07-24T16:21:06.724+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='QuangBLM1' AIRFLOW_CTX_DAG_ID='tunestream_etl_pipeline' AIRFLOW_CTX_TASK_ID='Stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T16:20:55.060184+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T16:20:55.060184+00:00'
[2025-07-24T16:21:06.733+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T16:21:06.787+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T16:21:06.800+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/final_exam_src.py", line 79, in load_songs_into_table
    postgres_hook.run(insert_sql, parameters=(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-07-24T16:21:06.813+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=tunestream_etl_pipeline, task_id=Stage_songs, run_id=manual__2025-07-24T16:20:55.060184+00:00, execution_date=20250724T162055, start_date=20250724T162106, end_date=20250724T162106
[2025-07-24T16:21:06.838+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task Stage_songs (The conn_id `postgres_default` isn't defined; 187)
[2025-07-24T16:21:06.890+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-24T16:21:06.911+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
