[2025-07-25T07:26:32.386+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T07:26:32.470+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Run_data_quality_checks scheduled__2025-07-24T14:00:00+00:00 [queued]>
[2025-07-25T07:26:32.498+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Run_data_quality_checks scheduled__2025-07-24T14:00:00+00:00 [queued]>
[2025-07-25T07:26:32.501+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-25T07:26:32.567+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Run_data_quality_checks> on 2025-07-24 14:00:00+00:00
[2025-07-25T07:26:32.586+0000] {standard_task_runner.py:63} INFO - Started process 954 to run task
[2025-07-25T07:26:32.595+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_pipeline', 'Run_data_quality_checks', 'scheduled__2025-07-24T14:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/final_exam_src.py', '--cfg-path', '/tmp/tmpy97rfx1j']
[2025-07-25T07:26:32.601+0000] {standard_task_runner.py:91} INFO - Job 212: Subtask Run_data_quality_checks
[2025-07-25T07:26:32.869+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_pipeline.Run_data_quality_checks scheduled__2025-07-24T14:00:00+00:00 [running]> on host f0ac0c7b7f5e
[2025-07-25T07:26:33.159+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='QuangBLM1' AIRFLOW_CTX_DAG_ID='tunestream_etl_pipeline' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T14:00:00+00:00'
[2025-07-25T07:26:33.165+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T07:26:33.206+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-25T07:26:33.227+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songplays, parameters: None
[2025-07-25T07:26:33.230+0000] {sql.py:496} INFO - Rows affected: 1
[2025-07-25T07:26:33.233+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T07:26:33.258+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/final_exam_src.py", line 165, in data_quality_check
    raise AirflowException(f"Data quality check failed for table {table}. No records found.")
airflow.exceptions.AirflowException: Data quality check failed for table songplays. No records found.
[2025-07-25T07:26:33.279+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl_pipeline, task_id=Run_data_quality_checks, run_id=scheduled__2025-07-24T14:00:00+00:00, execution_date=20250724T140000, start_date=20250725T072632, end_date=20250725T072633
[2025-07-25T07:26:33.318+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 212 for task Run_data_quality_checks (Data quality check failed for table songplays. No records found.; 954)
[2025-07-25T07:26:33.389+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T07:26:33.435+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
